reviews-section-done
oomloud/project-BetterThanGPT pull request #26
Opened 2023-06-05 17:17 UTC by keugenich

2023-06-05 20:54 UTC, oomloud requested changes
В цілому, все майже добре, тільки я трохи намучився з конфліктами. На майбутнє: комітити треба тільки свої файли, інші або ревертнеш, або просто не додаєш

2023-06-05 20:54 UTC, oomloud commented on src/partials/08_reviews.html
> +        <img
до зображення треба додати атрибут loading="lazy"

2023-06-05 20:54 UTC, oomloud commented on src/partials/08_reviews.html
> +        <img
до зображення треба додати атрибут loading="lazy"

2023-06-05 20:54 UTC, oomloud commented on src/partials/08_reviews.html
> +        <img
до зображення треба додати атрибут loading="lazy"

2023-06-05 20:54 UTC, oomloud commented on src/partials/08_reviews.html
> +  <button type="button" class="btn-big">Leave a review</button>
крім .btn-big треба додати додатковий стиль .btn-outline-light

2023-06-05 20:54 UTC, oomloud commented on src/partials/03_advantages.html
чужі файли не треба коммітити, тільки що відносяться до твоєї роботи

2023-06-05 20:54 UTC, oomloud commented on src/partials/01_header.html
чужі файли не треба коммітити, тільки що відносяться до твоєї роботи

2023-06-06 08:18 UTC, keugenich commented on src/partials/08_reviews.html
> +  <button type="button" class="btn-big">Leave a review</button>
Додано

2023-06-06 08:18 UTC, keugenich commented on src/partials/08_reviews.html
> +        <img
Додано

2023-06-06 08:18 UTC, keugenich commented on src/partials/08_reviews.html
> +        <img
Додано

2023-06-06 08:18 UTC, keugenich commented on src/partials/08_reviews.html
> +        <img
Додано

2023-06-06 14:10 UTC, oomloud approved these changes
дякую!

2023-06-06 14:10 UTC, merged