Modal buy second
oomloud/project-BetterThanGPT pull request #29
Opened 2023-06-05 22:33 UTC by evgen122

2023-06-06 18:14 UTC, oomloud requested changes
необхідно ще оптимізувати пнг файли, можна масово ось тут: https://tinypng.com

2023-06-06 18:14 UTC, oomloud commented on src/partials/11_modal_buy.html
> +<div class="buy-overlay-modal buy-is-hidden" data-modal-buy>
не зображається оверлей

2023-06-06 21:40 UTC, evgen122 commented on src/partials/11_modal_buy.html
> +                <img class="img-styles"
виправлено

2023-06-06 21:42 UTC, evgen122 commented on src/partials/11_modal_buy.html
> +                <img class="img-styles"
виправлено

2023-06-06 21:42 UTC, evgen122 commented on src/partials/11_modal_buy.html
> +                <input class="buy-modal-form-input" type="email" name="email" id="modal-email"
випралено

2023-06-06 21:45 UTC, evgen122 commented on src/partials/11_modal_buy.html
> +<div class="buy-overlay-modal buy-is-hidden" data-modal-buy>
Виправлено, але на макеті неясно яким кольором. Поставив на свій розсуд

2023-06-06 21:45 UTC, evgen122 commented on src/partials/11_modal_buy.html
> +                <input class="buy-modal-form-input buy-mastercard" type="number" name="userphon"
виправлено

2023-06-06 21:51 UTC, evgen122 commented on package-lock.json
Видалив

2023-06-07 08:38 UTC, oomloud approved these changes

2023-06-07 08:38 UTC, merged