Feature/explore new chocolate
oomloud/project-BetterThanGPT pull request #6
Opened 2023-06-03 12:00 UTC by VanUaTu1

2023-06-03 21:48 UTC, oomloud requested changes

2023-06-03 21:48 UTC, oomloud commented on package-lock.json
Цей файл не потрібно коммітити

2023-06-03 21:48 UTC, oomloud commented on src/img/icons.svg
Чомусь розбився файл з іконками, краще його ревертнути до попереднього стану. Можна зробити мердж з мейн

2023-06-03 21:48 UTC, oomloud commented on src/index.html
index.html так само не треба чіпати. Мерджом з мейну мало б фікснутися

2023-06-03 21:48 UTC, oomloud commented on src/partials/13_modal_explore.html
> +    <div class="explore-overlay" data-modal>
потрібно прибрати все крім коду всередині div class="explore-modal". Інакше воно розіб'є все на  main

2023-06-03 21:48 UTC, oomloud commented on src/partials/13_modal_explore.html
> +    <script src="../js/13_modal_explore.js"></script>
свій скрипт потрібно додати в папку JS і прописати як імпорт в main.js
![image](https://github.com/oomloud/project-BetterThanGPT/assets/47818790/1dd6a8b8-3dce-4892-b42a-2c7017c84711)

2023-06-04 09:21 UTC, VanUaTu1 commented
Зробив мердж

2023-06-04 13:35 UTC, oomloud approved these changes

2023-06-04 13:35 UTC, oomloud commented on src/index.html
> +    <link rel="stylesheet" href="./css/13_modal_explore.css" />
цей файл вже є підключений через styles.css

2023-06-04 13:36 UTC, oomloud approved these changes

2023-06-04 13:36 UTC, merged