Feature/how its made
oomloud/project-BetterThanGPT pull request #7
Opened 2023-06-03 13:38 UTC by DenisChornui

Finish section how_its_made.

2023-06-03 22:22 UTC, oomloud requested changes
В цілому все супер, тільки треба прибрати package-lock.json щоб випадково не пошкодити речі. Мердж з мейну мав би вирішити.

Зайве зображення - не критично

2023-06-03 22:22 UTC, oomloud commented on package-lock.json
Цей файл не треба коммітити

2023-06-04 14:08 UTC, DenisChornui commented on src/img/how_its_made/image.jpg
Зрозумів)

2023-06-04 14:09 UTC, DenisChornui commented on package-lock.json
видалити його і зробити коміт? і потім знову пулл?

2023-06-04 14:47 UTC, oomloud commented on package-lock.json
вирішив в режимі конфлікту :)

2023-06-04 14:47 UTC, oomloud approved these changes

2023-06-04 14:48 UTC, merged