Footer
oomloud/project-BetterThanGPT pull request #8
Opened 2023-06-03 14:04 UTC by VladBryzhak

Через валідатор код пропускав, були тільки помилки пов'язані із відсутністю Doctype i main. У мене там були деякі проблеми із марджинами і падінгами, тому я точно не знаю, чи все буде співпадати.

2023-06-03 18:39 UTC, oomloud requested changes

2023-06-03 18:39 UTC, oomloud commented on package-lock.json
Цей файл не треба коммітити, тільки те, що стосується сторінки

2023-06-03 18:39 UTC, oomloud commented on src/css/10_footer.css
> +@media only screen and (min-width: 768px) {
зайвий порожній медіа запит

2023-06-03 18:39 UTC, oomloud commented on src/css/10_footer.css
> +
не вистачає стиля .footer-nav-link та ховер/фокус ефектів до нього

2023-06-03 18:39 UTC, oomloud commented on src/css/10_footer.css
> +
не вистачає стиля .footer-social-link та ховер/фокус ефектів до нього

2023-06-03 18:39 UTC, oomloud commented on src/css/10_footer.css
> +.footer-container{
маю підозру, що бекграунд має розтягуватись на всю ширину вікна, але це не точно :)
можливо додай стиль фона на footer, а якщо ментор попросить, то повернемо назад

2023-06-03 18:56 UTC, VladBryzhak commented on src/css/10_footer.css
> +.footer-container{
Ну я спробую, але мені здається, там ломалося щось, коли додавав стиль на footer

2023-06-03 23:31 UTC, oomloud commented on src/css/10_footer.css
> +.footer-container{
достатньо просто перенести background-color і більше нічого

2023-06-04 09:59 UTC, VladBryzhak commented on src/css/10_footer.css
> +@media only screen and (min-width: 768px) {
Виправив

2023-06-04 09:59 UTC, VladBryzhak commented on src/css/10_footer.css
> +
Виправив

2023-06-04 09:59 UTC, VladBryzhak commented on src/css/10_footer.css
> +
Виправив

2023-06-04 09:59 UTC, VladBryzhak commented on src/css/10_footer.css
> +.footer-container{
Додав на футер, але воно ніби нічого не змінює

2023-06-04 10:02 UTC, VladBryzhak commented on src/css/10_footer.css
> +.footer-container{
І ще додав  на номер телефону і e-mail - ховер/фокус ефекти

2023-06-04 11:19 UTC, VladBryzhak commented on package-lock.json
Що робити із цим файлом я трохи не зрозумів....Якщо його так залишити, воно щось змінить?

2023-06-04 12:33 UTC, oomloud requested changes

2023-06-04 12:33 UTC, oomloud commented on src/css/10_footer.css
> +.footer-container{
працює :)
ти забув додати класс до тегу footer `<footer class="footer">`

2023-06-04 12:33 UTC, oomloud commented on src/css/10_footer.css
> +.footer-address-list-item:hover,
додай, будь ласка, і анімації переходу при ховері

2023-06-04 12:33 UTC, oomloud commented on src/partials/10_footer.html
> +<footer>
додай класс до тегу footer <footer class="footer">

2023-06-04 12:47 UTC, VladBryzhak commented on src/css/10_footer.css
> +.footer-address-list-item:hover,
Додав)

2023-06-04 12:48 UTC, VladBryzhak commented on src/partials/10_footer.html
> +<footer>
Додав)

2023-06-04 12:52 UTC, merged